ext.owned_kernel_primary_1211 = (gradle.ext.ownedKernelMode == 'primary').toString()
ext.owned_kernel_modern = (gradle.ext.ownedKernelMode == 'modern').toString()
ext.owned_kernel_yarn = (gradle.ext.ownedKernelMode == 'yarn').toString()

allprojects {
    group = 'dev.lodekeeper'
    version = rootProject.mod_version
    repositories { mavenCentral() }
}
subprojects {
    apply plugin: 'java-library'
    java { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 17 }
}
subprojects {
    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
    }
    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        maxHeapSize = '256m'
        maxParallelForks = 1
    }
}
