plugins { id 'fabric-loom' version '1.6.12' apply false }
allprojects {
    group = 'dev.lodekeeper'
    version = rootProject.mod_version
    repositories { mavenCentral() }
}
subprojects {
    apply plugin: 'java-library'
    java { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 17 }
}
subprojects {
    dependencies { testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2' }
    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        maxHeapSize = '256m'
        maxParallelForks = 1
    }
}
